apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - managed.quayregistry.yaml
secretGenerator:
- name: skynet-config-bundle
  files:
  - config.yaml
  options:
    disableNameSuffixHash: true